# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list
configuration :
- name : alice
  ip   : ec2-52-91-211-230.compute-1.amazonaws.com
  port : 12344
- name : bob
  ip   : ec2-52-91-211-230.compute-1.amazonaws.com
  port : 14255
- name : charlie
  ip   : ec2-54-152-89-119.compute-1.amazonaws.com
  port : 12998
- name : daphnie
  ip   : ec2-54-152-89-119.compute-1.amazonaws.com
  port : 1987
- name : ellis
  ip   : ec2-54-86-212-66.compute-1.amazonaws.com
  port : 12323
- name : frank
  ip   : ec2-54-86-212-66.compute-1.amazonaws.com
  port : 2567
- name : gavin
  ip   : ec2-52-87-206-141.compute-1.amazonaws.com
  port : 6754

# This is the incoming port on which MP will listen
# May be changed for further communication as usual
sendRules :
  - action : delay
    src    : bob
    kind   : notify
  - action : drop
    src    : alice
    dest   : charlie
    kind   : drop
receiveRules :
  - action : drop
    src    : alice
    dest   : bob
    kind   : drop2
groups :
  - name : Group1
    members :
      - alice
      - daphnie
      - ellis
  - name : Group2
    members :
      - bob
      - alice
      - frank
  - name : Group3
    members :
      - charlie
      - alice
      - gavin
  - name : Group4
    members :
      - daphnie
      - bob
      - charlie
  - name : Group5
    members :
      - ellis
      - bob
      - gavin
  - name : Group6
    members :
      - frank
      - charlie
      - ellis
  - name : Group7
    members :
      - gavin
      - daphnie
      - frank                        
# A single, top-level section in the YAML file
# Group names must be unique
# Any number of members in the group
# As many groups as you’d like 
 
# To Specify the total number of proccesses
processSize: 7
