# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node’s name is included in this list
configuration :
- name : alice
  ip   : ec2-52-91-211-230.compute-1.amazonaws.com
  port : 12344
- name : bob
  ip   : ec2-52-91-211-230.compute-1.amazonaws.com
  port : 14255
- name : charlie
  ip   : ec2-54-152-89-119.compute-1.amazonaws.com
  port : 12998
- name : daphnie
  ip   : ec2-54-152-89-119.compute-1.amazonaws.com
  port : 1987
# This is the incoming port on which MP will listen
# May be changed for further communication as usual
sendRules :
  - action : delay
    src    : alice
    kind   : delay
  - action : drop
    src    : alice
    kind   : drop
  - action : dropAfter
    src    : alice
    kind   : dropAfter  
    seqNum : 8
receiveRules :
  - action : dropAfter
    src    : a
    kind   : dropAfter  
    seqNum : 8
  
# To Specify the total number of proccesses
processSize: 4
